# Generated by Django 5.1.3 on 2024-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticklist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
