# Generated by Django 5.1.3 on 2024-11-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ticklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticklist',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
